spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:db/migration/init_h2.sql';
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
flyway:
  baseline-on-migrate: true
  
security:
  sessions: stateless
  enable-csrf: false

scrab:
  cors:
    enabled: true
  
  
logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework: INFO
    org.hibernate: WARN