#server:
#  port: 8080

spring:
  resources:
    add-mappings: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:db/migration/init_h2.sql';
flyway:
  init-on-migrate: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO